### ISSUE TITLE
python-qt5 5.6 sürümü sonrası çalışmıyor

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/package-manager#12]
ayhan@pisi20 ~ $ package-manager
Traceback (most recent call last):
  File "/usr/bin/package-manager", line 28, in <module>
    import backend
  File "/usr/share/package-manager/backend/**init**.py", line 16, in <module>
    import pisi.iface as pm
  File "/usr/share/package-manager/backend/pisi/iface.py", line 19, in <module>
    from pmutils import get_real_paths
  File "/usr/share/package-manager/pmutils.py", line 48, in <module>
    KIconLoader = QIconLoader(Pds)
  File "/usr/lib/python2.7/site-packages/pds/qiconloader.py", line 74, in **init**
    self.pds.session.DefaultIconTheme)
  File "/usr/lib/python2.7/site-packages/pds/**init**.py", line 101, in settings
    if path.exists(str(self.config_file)):
  File "/usr/lib/python2.7/site-packages/pds/**init**.py", line 78, in **getattr**
    raise AttributeError, name
AttributeError: config_file

**Comment by mthnzbk** [comment]
Şu anlık sorun yok.
