### ISSUE TITLE
Güncelleme sekmesine tıklanıldığında verdiği hata.

### ISSUE THREAD

**Issue by mthnzbk** [PisiLinuxNew/package-manager#16]
libpng warning: iCCP: known incorrect sRGB profile
False
2016-08-06 20:25:40,118 DEBUG   Updating repositories...
DEBUG:package-manager:Updating repositories...
2016-08-06 20:25:40,496 DEBUG   Signal: started
DEBUG:package-manager:Signal: started
2016-08-06 20:25:40,496 DEBUG   Args: (dbus.String(u'System.Manager.updateAllRepositories'),)
DEBUG:package-manager:Args: (dbus.String(u'System.Manager.updateAllRepositories'),)
2016-08-06 20:25:43,837 DEBUG   Signal: finished
DEBUG:package-manager:Signal: finished
2016-08-06 20:25:43,837 DEBUG   Args: (dbus.String(u'System.Manager.updateAllRepositories'),)
DEBUG:package-manager:Args: (dbus.String(u'System.Manager.updateAllRepositories'),)
False
2016-08-06 20:25:44,268 ERROR   Traceback (most recent call last):
  File "/usr/share/package-manager/packagedelegate.py", line 125, in paint
    self.paintInfoColumn(painter, option, index)
  File "/usr/share/package-manager/packagedelegate.py", line 251, in paintInfoColumn
    p.drawRoundRect(widthOfTitle, top + 12, rect.width() + 4, rect.height(), 10, 10)
AttributeError: 'QPainter' object has no attribute 'drawRoundRect'

ERROR:package-manager:Traceback (most recent call last):
  File "/usr/share/package-manager/packagedelegate.py", line 125, in paint
    self.paintInfoColumn(painter, option, index)
  File "/usr/share/package-manager/packagedelegate.py", line 251, in paintInfoColumn
    p.drawRoundRect(widthOfTitle, top + 12, rect.width() + 4, rect.height(), 10, 10)
AttributeError: 'QPainter' object has no attribute 'drawRoundRect'

QPaintDevice: Cannot destroy paint device that is being painted

**Comment by mthnzbk** [comment]
drawRoundRect yerine drawRoundedRect olmalı sanırım.

**Comment by mthnzbk** [comment]
https://github.com/PisiLinuxNew/package-manager/commit/9caa4791c20fff7d49fa2375a8a587da61b2e5f5 ile çözüldü.
