### ISSUE TITLE
pacakge-manager 4.1.6 has error

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [PisiLinuxNew/package-manager#17]
ayhan@ayhan-pc ~ $ package-manager
ayhan@ayhan-pc ~ $ Traceback (most recent call last):
  File "/usr/bin/package-manager", line 67, in <module>
    manager = MainWindow(app)
  File "/usr/share/package-manager/mainwindow.py", line 65, in **init**
    self.settingsDialog = SettingsDialog(self)
  File "/usr/share/package-manager/settingsdialog.py", line 463, in **init**
    self.initialize()
  File "/usr/share/package-manager/settingsdialog.py", line 467, in initialize
    self.generalSettings = GeneralSettings(self)
  File "/usr/share/package-manager/settingsdialog.py", line 43, in **init**
    self.setupUi()
  File "/usr/share/package-manager/settingsdialog.py", line 73, in setupUi
    self.initialize()
  File "/usr/share/package-manager/settingsdialog.py", line 80, in initialize
    self.settings.intervalCheck.setChecked(self.config.updateCheck())
  File "/usr/share/package-manager/config.py", line 70, in updateCheck
    return int(self.value("UpdateCheck") or 0)
ValueError: invalid literal for int() with base 10: 'true'

**Comment by hrngultekin** [comment]
Ayar dosyasını (.config/Pisi/package-manager.conf) silin
